### ISSUE TITLE
There is still a problem with wallet synchronization. After a long time on the Internet, I still haven’t got half a coin.

### ISSUE THREAD

**Issue by Nok74** [denisio/seno-blockchain#10]
Wallet height: 753
Sync status: Not synced
Balances, fingerprint: 2952494445
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 xse (0 mojo)
   -Pending Total Balance: 0.0 xse (0 mojo)
   -Spendable: 0.0 xse (0 mojo)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EFC70C6F70>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by Hedonay** [comment]
Tr this: https://github.com/denisio/seno-blockchain/issues/8#issuecomment-869672565

**Comment by sergiosurvival** [comment]
somos 2 no sincroniza ni desistalando 40 veces xd....!!

**Comment by sergiosurvival** [comment]
![2021-09-25](https://user-images.githubusercontent.com/83919237/134749096-f69f89fb-b5e0-4ba1-afe2-ff8a9f503227.png)

**Comment by sergiosurvival** [comment]
121.172.131.105 | 18444

82.61.78.80 | 18444
37.79.213.110 | 18444
86.122.69.190 | 18444
79.116.4.112 | 18444
2.80.12.127 | 18444
113.190.202.233 | 18444

**Comment by sergiosurvival** [comment]
not sincroniced

**Comment by sergiosurvival** [comment]
not sincronize
