### ISSUE TITLE
can not install with ubuntu

### ISSUE THREAD

**Issue by SatoKentaNayoro** [denisio/seno-blockchain#11]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/hxc/seno-blockchain/venv/bin/python /home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpov6_iyyj
         cwd: /home/hxc/seno-blockchain
    Complete output (32 lines):
    Traceback (most recent call last):
      File "/home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 117, in <module>
        setup(**kwargs)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 801, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 808, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 176, in _get_version
        version_string = format_version(
      File "/tmp/pip-build-env-y7nl8y81/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 447, in format_version
        assert main_version is not None
    AssertionError
    ----------------------------------------
WARNING: Discarding file:///home/hxc/seno-blockchain. Command errored out with exit status 1: /home/hxc/seno-blockchain/venv/bin/python /home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpov6_iyyj Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/hxc/seno-blockchain/venv/bin/python /home/hxc/seno-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpov6_iyyj Check the logs for full command output.

**Comment by denern** [comment]
You need to clean old seno-blockchain and do git clone.

**Comment by xsilmarx** [comment]
I get this error with fresh install, running on ubuntu docker image 21.04.
Chia is installing correctly with the same image.
