### ISSUE TITLE
IP list of full Active Nodes

### ISSUE THREAD

**Issue by kiryandex** [denisio/seno-blockchain#13]
Hi, can someone share a list of active or introducer nodes with IPs for manual connection?

**Comment by denisio** [comment]
95.163.12.167

**Comment by t0l0** [comment]
@kiryandex 
You can find out with
`dig dns-introducer.seno.uno`

@denisio 
Currently no connection seems possible:
```
C:\Users\XXX\AppData\Local\seno-blockchain\app-1.1.834\resources\app.asar.unpacked\daemon>seno show -a 95.163.12.167:18444
Connecting to 95.163.12.167, 18444
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002872629DD30>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

Port seems open, though
