### ISSUE TITLE
Connected with introducer problem

### ISSUE THREAD

**Issue by pantgr** [denisio/seno-blockchain#5]
2021-06-28T12:57:30.881 full_node full_node_server        : INFO     Connected with introducer {'host': 'introducer.seno.uno', 'port': 18445}
2021-06-28T12:57:31.133 full_node full_node_server        : INFO     Connection closed: introducer.seno.uno, node id: a1************************************************************a1c31a
2021-06-28T12:57:31.133 full_node seno.full_node.full_node: INFO     peer disconnected {'host': '89.*.*.*', 'port': 18445}
2021-06-28T12:57:31.134 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '89.*.*.*', 'port': 18445}. Traceback (most recent call last):
  File "/home/pant/seno-blockchain/seno/server/server.py", line 539, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError

This massage repaired and  repaired on logs

**Comment by denisio** [comment]
CA keys updated. Please, reinstall all with remove ~/.seno config.

**Comment by pantgr** [comment]
all rdy done this is new compile thanks

**Comment by pantgr** [comment]
also get and this errror :
 File "/home/pant/seno-blockchain/seno/server/server.py", line 539, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError

if helps thanks

**Comment by pantgr** [comment]
fixated by deleting and re-enter the mechanic words thanks.
